### PR TITLE
Linked resources

### PR DESCRIPTION
**Pull request by loleg**
Initial draft of #208

Screenshot from 2020-11-12 11-52-59

Preview: https://dribdat-test.herokuapp.com/

### CODE REVIEW

**Comment by loleg** [comment]
Currently just a simple drop down, I imagine this becoming an auto-complete or gallery select in the near future. Or just click on the suggestion from your project tips screen to "adopt" it.

Screenshot from 2020-11-12 20-50-57

Note the "suggest further resources" link. Any resources users add become immediately visible (unless `DRIBDAT_SHOW_SUBMITS` is toggled), but not recommended until administrators select a progress level for them. 

Speaking of progress, here is how a Post looks like with a resource attached:

Screenshot from 2020-11-12 20-49-38

I'm not sure a project needs a separate "Sources" tab if the Log presents this adequately. Perhaps it could just be a toggle on the Log screen.

**Comment by loleg** [comment]
Initial aggregation from Data Packages has been added. It is still work in progress, but I think this PR is close to being ready. In my testing it seems quite steady, anyway.

Also, it is now possible to see your own (or another user's) posts on the profile page:

Screenshot from 2020-11-13 13-24-39

**Comment by gonzalocasas** [comment]
So, if I get it right, admins can configure resources (per project stage?) which are displayed on the project page's pitch tab if the user is a member of the project. So far, so good, but perhaps this should go to a tab on its own? `Resources` maybe?

What gets trickier is the `Post` page, I don't really understand the link between a post and a resource. At some level, I think all this custom fields are not making it easier to use, and we could have a markdown-enabled big text box where these resources can be linked as well, and that would make it easier.

**Comment by loleg** [comment]
Thanks for the observations. When you attach a link to a Tweet from a site which supports OEmbed (or is it OpenGraph?), it gets rendered in a box. You're sharing a story, a recommendation, and the context is proudly featured. 

I don't want the experience of using Dribdat to feel like filling out a bunch of forms. (At risk of being thrown off the Internet) I would also say that a chatbot alone doesn't change form filling out much either. Hence I want our experience of discovering and playing with tools and data sources to be brought close together.

Dribdat should let us search through everything the organizers have prepared in terms of material (at TTN events this would include circuit schematics and chip specs), and quickly sharing (maybe a star should suffice, without even the need to comment) their interest in it. We shouldn't have to use a separate website or tool to do this when it is central to our activities.

Plus, we should be collecting structured data about what else people bring into an event. The key instrument here is the ability to suggest a dataset or resource, something we've always had a form or email address for.

I wonder if at some level you still hold the opinion that Dribdat should just scrape and aggregate into `hackathon.json`? I have wondered as well what a separately coded but tightly integrated process, a shared hacker's toolbox, would look like here.

The closest that comes to mind are IDE enhancers like [vim plugins](https://vimawesome.com/), [Atom packages](https://atom.io/packages) or [Jupyter extensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/index.html) - to understand how a coder works, you would need to see what their environment is like. To reproduce a good hack, it would help to see what were the enabling factors.

**Comment by loleg** [comment]
@gonzalocasas re: "we could have a markdown-enabled big text box where these resources can be linked as well, and that would make it easier."

I have given it more thought: yes, for some people it is easier. Nothing prevents them from doing this, and in fact our existing dribdat instances are full of links to resources all over the Internet. Something should be done about that ;-)

In the meantime, having the ability to explicitly connect projects to 'packaged', i.e. recommended resources should be an interesting way to make more sense of the sometimes chaotic jumble of activities at a hackathon. I definitely think the interface and everything here is very V1.0, but I'd like to test the hypothesis. Therefore, releasing early and often!

**Pull request merged**
