### PR TITLE
Project view in tabs

### LINKED ISSUE #175: Make external content more prominent
When a team decides to mostly document in a README, the sync'ed content should be more prominent than the local content. Perhaps we could decide based on the content-length and position accordingly. 

Additionally, the feature of [dribdat2](https://github.com/hackathons-ftw/dribdat2_frontend) which visualizes contribution histories and other data from the remote location would be great to explore, even just in the form of a small banner making it clear where the content is coming from.

While we're at it, how hard would it to be to support multiple externals, i.e. a slideshow, data science notebook, scrapbook ...

### PR DESCRIPTION
**Pull request by loleg**
Cleans up the UI of project views by splitting the content across Presentation, Documentation, Readme, Signals tabs. When JavaScript is disabled the content is still presented in a long scroll. 

The content of progress Posts now goes into the activities, instead of the description.

The Signals tab is a new view of information that was kind of hidden before: the interactions of the team with the project. This shows the new progress reports as well. Quick screenshot:

Screenshot from 2020-10-11 12-10-57

The timeline component is from https://github.com/sandroanderes/GLAMhack2020 - a hackathon project from [GLAMhack 2020](https://hack.glam.opendata.ch/project/14) by @sandroanderes

Resolves #175

### CODE REVIEW

**Comment by loleg** [comment]
Deployed to https://hacknight.dinacon.ch/

@gonzalocasas you can see the new [project layout here](https://hacknight.dinacon.ch/project/33), for example. Thanks for your feedback!

**Comment by gonzalocasas** [comment]
It looks really really cool! The only thing I would change is the gradient style of the headers, I would use a flat color and remove the  slightly dark-red shadow of the text. But if you prefer to leave that as default style, as long as it's overridable with custom CSS it's all fine and dandy ;)

**Comment by loleg** [comment]
It's definitely overridable, check `timeline.css`. For example, if you wanted more tropical flavour in your logs:

```css
.timeline-img-header h2 { color: lightgreen; }
.timeline::before, .timeline-img { background: yellow; }
.timeline-img-header { background: orange; }
.timeline-item:nth-child(even) .timeline-content::after { border-color: transparent transparent transparent orange; }
.timeline-item:nth-child(odd) .timeline-content::after { border-color: transparent orange transparent transparent; }
```

**Comment by loleg** [comment]
Feedback from review incorporated, tested and tagged. Thanks again @gonzalocasas

**Pull request merged**
