### PR TITLE
Switch to github actions

### PR DESCRIPTION
**Pull request by gonzalocasas**
Migrate CI to github actions and add builds on all platforms on cpython 3.6, 3.7 and 3.8.

### CODE REVIEW

**Comment by loleg** [comment]
Wow, thanks @gonzalocasas

Now we can think of what plugins to add, like notification of Mattermost or Twitter.

**Comment by gonzalocasas** [comment]
Not sure what your protocol is, do you merge this? or shall I?

**Review by loleg — APPROVED** [review]

**Comment by loleg** [comment]
My one tweak would be to only configure for test runs of Linux builds, since this isn't a desktop app. There is a warning about Ubuntu in the test run:

> Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816 

You're welcome to merge it.

**Comment by gonzalocasas** [comment]
I fixed the warning for ubuntu by adding explicit runs on 18.04 and 20.04. About removing the other OSes, I added them not thinking this is a desktop app, but thinking of the (poor) devs who have to work on Windows computers and still wish to contribute to Dribdat. But I can remove them if you feel it's silly to keep them.

**Comment by loleg** [comment]
Just for future reference, this is quite a handy guide: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

**Pull request merged**
