### PR TITLE
Gamify me

### PR DESCRIPTION
**Pull request by loleg**
This adds a long requested ability for admins to award special badges to projects, as well as an equally long awaited ability for all users to start an event if the site owners allow it. See #87 and https://github.com/dribdat/gamification for the inspiration.

- Regular users can now start events with the option `ALLOW_EVENT` setting #231
- Admins can add a "booster post" to a project with a pre-defined list of award types #7
- The timeline now features icons relevant to the type of update (see screenshot)
- Boosters are also shown next to the project name, linked to the log, and in the user profile.
- Admins can now delete posts from the project log, and add and remove team members*
- Minor improvements have been made to resource recommendations #249
- Slight reworking of the event header and footer layouts. The top navigation has been updated for usability.
- The Post interface has been improved and made accessible from more locations in the app.
- Top 10 issues are shown next to the GitHub widget, when available.
- Our simple Search and API page is now linked in the navigation (woot!)
- Refactoring, linting, and dependency upgrades.

gloriouspurpose

### 🚧  Developer notes

- If auto upgrading of your instance does not complete, you may require a manual SQL entry to deploy to an existing site:
`ALTER TYPE activity_type ADD VALUE 'boost';`
- Note that non-admins can only propose, not yet edit or publish, events that they start (they are warned about this)
- The new interface to removing (little x button) or adding (you have to enter the exact username) team members is very basic and admin-only for now:
Screenshot from 2021-09-23 00-48-46

### CODE REVIEW

**Comment by loleg** [comment]
Deployed and configured on meta for testing.

**Comment by gonzalocasas** [comment]
@loleg is the build fail something to worry about?

**Comment by loleg** [comment]
> @loleg is the build fail something to worry about?

Not ... really ... looks like a weird package manager issue to me. The tests on Python 3.9 pass for me on local. Anyway I'll push a fresh update to try the build again and dig into it later.

**Comment by loleg** [comment]
I've managed to reproduce the error, which is a [dependency issue](https://github.com/python-poetry/poetry/issues/4402). Thanks for pointing it out @gonzalocasas  !

**Comment by loleg** [comment]
The interface to progress the projects has been slightly improved, and this guide created:

dribdat - How to Promote a Project

**Comment by loleg** [comment]
I've done a bit more final testing, tweaking - deployed to meta & schoolofdata for public testing.

**Pull request merged**
